name: local_pyg
channels:
  - pytorch
  - nvidia
  - anaconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=py310h06a4308_0
  - aiohappyeyeballs=2.4.4=pyhd8ed1ab_1
  - aiohttp=3.11.10=py310h89163eb_0
  - aiosignal=1.3.1=pyhd8ed1ab_1
  - aom=3.5.0=h27087fc_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=24.2.0=pyh71513ae_1
  - blas=1.0=mkl
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.11.26=h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.8.30=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - curl=8.9.1=hdbd6064_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h52b45da_1
  - dav1d=1.2.0=hd590300_0
  - dbus=1.13.18=hb2f20db_0
  - double-conversion=3.2.0=h9c3ff4c_0
  - eigen=3.4.0=h4bd325d_0
  - expat=2.6.4=h5888daf_0
  - ffmpeg=5.1.2=gpl_h9866456_109
  - filelock=3.13.1=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.5.0=py310ha75aee5_0
  - gl2ps=1.4.2=h0708190_0
  - glew=2.2.0=h6a678d5_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h59595ed_1003
  - grpcio=1.62.2=py310h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=73.2=h59595ed_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsoncpp=1.9.5=h4bd325d_1
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libaec=1.1.3=h59595ed_0
  - libass=0.17.1=h8fe9dca_1
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.7.77=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=hac7e632_1003
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libgomp=14.2.0=h77fa898_1
  - libgrpc=1.62.2=h2d74bed_0
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnetcdf=4.9.1=nompi_h34a3ff0_101
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libogg=1.3.5=h4ab18f5_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=h4ab18f5_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.4=hfdd30dd_2
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - loguru=0.7.2=py310hff52083_2
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py310h06a4308_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-base=3.9.3=py310h68603db_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - msgpack-python=1.1.0=py310h3788b33_0
  - multidict=6.1.0=py310h89163eb_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.3=py310h06a4308_0
  - nlohmann_json=3.11.3=he02047a_1
  - nspr=4.36=h5888daf_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.10.1=py310h3c60e43_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.4.0=hb9d3cd8_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pandas=2.2.2=py310h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pooch=1.8.2=pyhd8ed1ab_1
  - proj=9.1.1=h8ffa02c_2
  - propcache=0.2.1=py310ha75aee5_0
  - protobuf=4.25.3=py310h12ddb61_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.11.4=h59595ed_1
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.2.0=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py310h06a4308_0
  - pyvista=0.44.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - qhull=2020.2=h4bd325d_2
  - qt=5.15.9=h06a4308_0
  - qt-main=5.15.2=hb6262e9_11
  - qt-webengine=5.15.9=h9ab4d14_7
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - scooby=0.10.0=pyhd8ed1ab_0
  - setuptools=75.1.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - svt-av1=1.4.1=hcb278e6_0
  - sympy=1.13.2=py310h06a4308_0
  - tbb=2021.9.0=hf52228f_0
  - tbb-devel=2021.9.0=hf52228f_0
  - tensorboard=2.17.0=py310h06a4308_0
  - tensorboard-data-server=0.7.0=py310h52d8a92_1
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.2.0=py310_cu121
  - torchtriton=2.2.0=py310
  - torchvision=0.17.0=py310_cu121
  - typing-extensions=4.11.0=py310h06a4308_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py310ha75aee5_1
  - urllib3=2.2.3=py310h06a4308_0
  - utfcpp=3.2.5=ha770c72_0
  - werkzeug=3.0.6=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - wslink=2.2.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_2
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.3=py310ha75aee5_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - addict==2.4.0
      - asttokens==3.0.0
      - blinker==1.9.0
      - click==8.1.7
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.0
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - flask==3.0.3
      - fonttools==4.54.1
      - importlib-metadata==8.5.0
      - ipython==8.30.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - open3d==0.18.0
      - packaging==24.1
      - parso==0.8.4
      - pexpect==4.9.0
      - plotly==5.24.1
      - prompt-toolkit==3.0.48
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyg-lib==0.4.0+pt22cu121
      - pygments==2.18.0
      - pyquaternion==0.9.9
      - referencing==0.35.1
      - retrying==1.3.4
      - rpds-py==0.22.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - stack-data==0.6.3
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - torch-cluster==1.6.3+pt22cu121
      - torch-geometric==2.2.0
      - torch-scatter==2.1.2+pt22cu121
      - torch-sparse==0.6.18+pt22cu121
      - torch-spline-conv==1.2.2+pt22cu121
      - tqdm==4.66.6
      - traitlets==5.14.3
      - vtk==9.3.1
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.13
      - zipp==3.21.0
prefix: /root/anaconda3/envs/local_pyg
